task :default => [:help]

verbose(false) # don't echo commands

task :help do
  puts "Help"
  puts "Testing: "
  puts "rake test             - Test everything"
  puts "rake test:unit        - Test units"
  puts "rake test:integration - Test integration"
  puts "rake test:handlers    - Test handlers"
  puts "Utilities: "
  puts "rake stats            - Code stats (LOC, etc.)"
end

desc "Test everything"
task :test do
  ruby "test/test.rb"
end

desc "Stats"
task :stats do
    begin
      require 'code_statistics/code_statistics'

      stats_directories = [
        %w(Libraries lib/),
        %w(Handlers app/handlers/)
      ].collect { |name, dir| [ name, "#{Dir.pwd}/#{dir}" ] }.select { |name, dir| File.directory?(dir) }

      puts CodeStatistics::CodeStatistics.new(stats_directories).to_s
    rescue LoadError
      puts "You need to install the code_statistics gem to use the stats task"
      puts "Install it using: "
      puts "$ bundle install"
    end
end

namespace :test do
  desc "Test units"
  task :unit do
    ruby "test/unit.rb"
  end

  desc "Test integration"
  task :integration do
    ruby "test/integration.rb"
  end

  desc "Test handlers"
  task :handlers do
    ruby "test/handlers.rb"
  end
end